### ISSUE TITLE
DeprecationWarning: initialize_ordered_bulk_op is deprecated

### ISSUE THREAD

**Issue by tashrifbillah** [harvard-nrg/dpimport#3]
This may be a harmless py2-->py3 conversion issue but we should fix it at some point:

https://github.com/harvard-nrg/dpimport/blob/main/scripts/import.py#L109

```vim
INFO:__main__:document exists and is up to date /home/tb571/project_data/GENERAL/STUDY/SUBJECT/phone/processed/STUDY-SUBJECT-phone_surveyTimings_logbook_daily-day1to154.csv
INFO:__main__:cleaning metadata
/home/tb571/min3-dpdash/bin/import.py:109: DeprecationWarning: initialize_ordered_bulk_op is deprecated
  bulk_metadata = db.metadata.initialize_ordered_bulk_op()
```

**Comment by blms** [comment]
I'll work on this as it concerns `pymongo` and MongoDB. For my reference:
- https://pymongo.readthedocs.io/en/stable/api/pymongo/collection.html#pymongo.collection.Collection.initialize_ordered_bulk_op
- https://pymongo.readthedocs.io/en/stable/api/pymongo/collection.html#pymongo.collection.Collection.bulk_write
